from . import person
from . import contact_person
from . import doctor_specialty
from . import medical_diagnosis
from . import doctor_schedule
from . import patient_doctor_history
from . import hr_hospital_library_doctor
from . import hr_hospital_library_patient
from . import hr_hospital_library_visit
from . import hr_hospital_disease_type